# Generated by Django 4.0.6 on 2022-07-09 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.TextField(default='', null=True)),
                ('date1', models.DateField(help_text='show date1', null=True)),
                ('date2', models.DateField(blank=True, help_text='show date1', null=True)),
                ('date3', models.DateField(blank=True, help_text='show date1', null=True)),
                ('trailer', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='theaterlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theater', models.CharField(max_length=20)),
                ('show_time', models.CharField(blank=True, choices=[(1, '9:30AM'), (2, '12:00PM'), (3, '2:30PM'), (4, '4:30PM'), (5, '6:30PM'), (6, '8:30PM')], max_length=10, null=True)),
                ('movies', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_seats', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
