# Generated by Django 4.0.6 on 2022-07-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_theaterlist_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='latest',
            field=models.BooleanField(default=0),
        ),
    ]
