# Generated by Django 4.0.6 on 2022-07-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_latest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theaterlist',
            name='show_time',
            field=models.IntegerField(blank=True, choices=[(1, '9:30AM'), (2, '12:00PM'), (3, '2:30PM'), (4, '4:30PM'), (5, '6:30PM'), (6, '8:30PM')], null=True),
        ),
    ]
