# Generated by Django 4.0.6 on 2022-07-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_theaterlist_show_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='date1',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='date2',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='date3',
        ),
        migrations.AddField(
            model_name='theaterlist',
            name='date1',
            field=models.DateField(help_text='show date1', null=True),
        ),
        migrations.AddField(
            model_name='theaterlist',
            name='date2',
            field=models.DateField(blank=True, help_text='show date1', null=True),
        ),
        migrations.AddField(
            model_name='theaterlist',
            name='date3',
            field=models.DateField(blank=True, help_text='show date1', null=True),
        ),
        migrations.AlterField(
            model_name='theaterlist',
            name='show_time',
            field=models.CharField(blank=True, choices=[('9:30AM', '9:30AM'), ('12:00PM', '12:00PM'), ('2:30PM', '2:30PM'), ('4:30PM', '4:30PM'), ('6:30PM', '6:30PM'), ('8:30PM', '8:30PM')], max_length=10, null=True),
        ),
    ]
