# Generated by Django 4.0.6 on 2022-07-11 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_remove_movie_date1_remove_movie_date2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theaterlist',
            old_name='show_time',
            new_name='show_time1',
        ),
        migrations.RemoveField(
            model_name='theaterlist',
            name='date1',
        ),
        migrations.RemoveField(
            model_name='theaterlist',
            name='date2',
        ),
        migrations.RemoveField(
            model_name='theaterlist',
            name='date3',
        ),
        migrations.AddField(
            model_name='theaterlist',
            name='show_time2',
            field=models.CharField(blank=True, choices=[('9:30AM', '9:30AM'), ('12:00PM', '12:00PM'), ('2:30PM', '2:30PM'), ('4:30PM', '4:30PM'), ('6:30PM', '6:30PM'), ('8:30PM', '8:30PM')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='theaterlist',
            name='show_time3',
            field=models.CharField(blank=True, choices=[('9:30AM', '9:30AM'), ('12:00PM', '12:00PM'), ('2:30PM', '2:30PM'), ('4:30PM', '4:30PM'), ('6:30PM', '6:30PM'), ('8:30PM', '8:30PM')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='theaterlist',
            name='show_time4',
            field=models.CharField(blank=True, choices=[('9:30AM', '9:30AM'), ('12:00PM', '12:00PM'), ('2:30PM', '2:30PM'), ('4:30PM', '4:30PM'), ('6:30PM', '6:30PM'), ('8:30PM', '8:30PM')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='theaterlist',
            name='show_time5',
            field=models.CharField(blank=True, choices=[('9:30AM', '9:30AM'), ('12:00PM', '12:00PM'), ('2:30PM', '2:30PM'), ('4:30PM', '4:30PM'), ('6:30PM', '6:30PM'), ('8:30PM', '8:30PM')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='theaterlist',
            name='show_time6',
            field=models.CharField(blank=True, choices=[('9:30AM', '9:30AM'), ('12:00PM', '12:00PM'), ('2:30PM', '2:30PM'), ('4:30PM', '4:30PM'), ('6:30PM', '6:30PM'), ('8:30PM', '8:30PM')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='show date1', null=True)),
                ('movies', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('theaterlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.theaterlist')),
            ],
        ),
    ]
