# Generated by Django 4.0.6 on 2022-07-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_rename_show_time_theaterlist_show_time1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='show_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_time', models.CharField(blank=True, choices=[('9:30AM', '9:30AM'), ('12:00PM', '12:00PM'), ('2:30PM', '2:30PM'), ('4:30PM', '4:30PM'), ('6:30PM', '6:30PM'), ('8:30PM', '8:30PM')], max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='theaterlist',
            name='movies',
        ),
        migrations.RemoveField(
            model_name='theaterlist',
            name='show_time1',
        ),
        migrations.RemoveField(
            model_name='theaterlist',
            name='show_time2',
        ),
        migrations.RemoveField(
            model_name='theaterlist',
            name='show_time3',
        ),
        migrations.RemoveField(
            model_name='theaterlist',
            name='show_time4',
        ),
        migrations.RemoveField(
            model_name='theaterlist',
            name='show_time5',
        ),
        migrations.RemoveField(
            model_name='theaterlist',
            name='show_time6',
        ),
        migrations.AddField(
            model_name='dates',
            name='show_time',
            field=models.ManyToManyField(blank=True, to='movie.show_time'),
        ),
    ]
