# Generated by Django 4.0.6 on 2022-07-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_remove_dates_show_time_theaterlist_show_time1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='no_seats',
        ),
    ]
