# Generated by Django 4.0.6 on 2022-07-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_seats_remove_booking_no_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='all_seat',
            field=models.ManyToManyField(blank=True, to='movie.seats'),
        ),
    ]
