# Generated by Django 4.0.6 on 2022-07-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_booking_all_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
