# Generated by Django 4.0.6 on 2022-07-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_alter_booking_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='all_seat',
        ),
        migrations.AddField(
            model_name='booking',
            name='all_seat',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
