# Generated by Django 4.0.6 on 2022-07-24 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_booking_date_booking_theater_booking_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='seats',
        ),
    ]
